var description = [
    {"vectorTileLayer": '显示一个矢量图层'},
    {'geoJsonFillLayer': '显示一个geoJson填充图层'},
    {'geoJsonIconLayer': '显示一个geoJson图标图层'},
    {'geoJsonLineLayer': '显示一个geoJson线图层'},
    {'geoJsonTextLayer': '显示一个geoJson文本图层'},
    {'GraphicsLayer': '显示一个几何要素图层'},
    {'GridTileLayer': '显示一个栅格图层'},
    {'vectorTileLayer': '显示一个矢量栅格图层'},
    {'area': '矢量绘制并测量面积'},
    {'distance': '拉线测量距离'},
    {'InitMapLayer': '初始化openLayer图层'},
    {'layerCountSet': '图层按照数量动态添加'},
    {'setDataScoure': '按照类别进行数据源切换'},
    {'addremove': '增加或移除图层'},
    {'Canvas': 'Canvas方式绘制图形'},
    {'ColorLayer': '采用色斑图形式进行图层渲染'},
    {'Contour': '采用等值线形式进行图层渲染'},
    {'drawREct': '拉框绘制矩形'},
    {'Image': '增加图片'},
    {'LayerSet': '图层显示隐藏、透明度、符号颜色设置'},
    {'line': '增加一个矢量线图层'},
    {'location': '增加定位显示'},
    {'mapbox': '初始化底图控件'},
    {'PBF': '解析PBF数据并显示'},
    {'Point': '增加一个矢量点图层'},
    {'Polygon': '增加一个矢量面图层'},
    {'Station': '增加一个站点填图信息'},
    {'Typhoon': '增加一个台风路径绘制图层'},
    {'touying': '投影转换'},
    {'visible': '控制显示隐藏'},
    {'VectorBaseMap': '增加矢量基础底图'},
]

